USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
CREATE DATABASE IF NOT EXISTS MYDB;
USE DATABASE MYDB;
CREATE SCHEMA IF NOT EXISTS PUBLIC;
USE SCHEMA PUBLIC;
CREATE
OR REPLACE TABLE STUDENTS (
    ID INT,
    NAME STRING,
    AGE INT,
    GENDER STRING,
    COURSE STRING,
    BRANCH STRING,
    YEAR INT,
    MARKS INT,
    CITY STRING,
    STUDENT_INFO STRING
);
CREATE
OR REPLACE FILE FORMAT my_csv_format TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"';
CREATE
OR REPLACE STAGE my_stage;
COPY INTO STUDENTS (NAME, COURSE, BRANCH, YEAR, MARKS, CITY)
FROM
    @my_stage/student.csv FILE_FORMAT = (FORMAT_NAME = my_csv_format);
UPDATE
    STUDENTS
SET
    BRANCH = UPPER(TRIM(BRANCH));
SELECT
    *
FROM
    STUDENTS;
DESC TABLE STUDENTS;